name: Build Android

on:
  push:
    branches:
      - master     # Ganti 'master' jika branch utamamu bernama master
  workflow_dispatch: # Agar bisa menjalankan build secara manual dari web GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode repositori
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Java JDK
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter Framework
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      # 4. Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5. Build APK (Release Mode)
      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation
      # 6. Upload File APK sebagai Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Daffa_Dwi_SulistiyoXIPPLG2
          path: build/app/outputs/Daffa_Dwi_SulistiyoXIPPLG2/tugas_wisata_daffa_05.apk